In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_excel('flight_price.xlsx')

In [3]:
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [4]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [5]:
df.shape

(10683, 11)

In [6]:
df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

In [7]:
df.dtypes

Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
dtype: object

In [8]:
df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [9]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [10]:
df.dropna(axis = 0 , inplace = True)

In [11]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
Price              0
dtype: int64

In [12]:
df['Date_of_Journey']

0        24/03/2019
1         1/05/2019
2         9/06/2019
3        12/05/2019
4        01/03/2019
            ...
10678     9/04/2019
10679    27/04/2019
10680    27/04/2019
10681    01/03/2019
10682     9/05/2019
Name: Date_of_Journey, Length: 10682, dtype: object

In [15]:
df['Day'] = df['Date_of_Journey'].str.split('/').str[0]
df['Month'] = df['Date_of_Journey'].str.split('/').str[1]
df['Year'] = df['Date_of_Journey'].str.split('/').str[2]

In [16]:
df['Day']

0        24
1         1
2         9
3        12
4        01
         ..
10678     9
10679    27
10680    27
10681    01
10682     9
Name: Day, Length: 10682, dtype: object

In [18]:
df['Day'] = df['Day'].astype(int)
df['Month'] = df['Month'].astype(int)
df['Year'] = df['Year'].astype(int)

In [19]:
df.dtypes

Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
Day                 int32
Month               int32
Year                int32
dtype: object

In [20]:
df.drop('Date_of_Journey',axis = 1 , inplace = True)

In [21]:
df.dtypes

Airline            object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
Day                 int32
Month               int32
Year                int32
dtype: object

In [25]:
df['Arrival_Time'] = df['Arrival_Time'].apply(lambda x:x.split(' ')[0])

In [26]:
df['Arrival_hour']= df['Arrival_Time'].str.split(':').str[0]
df['Arrival_minute']= df['Arrival_Time'].str.split(':').str[1]

In [27]:
df.dtypes

Airline            object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
Day                 int32
Month               int32
Year                int32
Arrival_hour       object
Arrival_minute     object
dtype: object

In [28]:
df['Arrival_hour']=df['Arrival_hour'].astype(int)
df['Arrival_minute']=df['Arrival_minute'].astype(int)

In [30]:
df.dtypes

Airline            object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
Day                 int32
Month               int32
Year                int32
Arrival_hour        int32
Arrival_minute      int32
dtype: object

In [32]:
df.drop('Arrival_Time',axis = 1 , inplace = True)

In [33]:
df.columns

Index(['Airline', 'Source', 'Destination', 'Route', 'Dep_Time', 'Duration',
       'Total_Stops', 'Additional_Info', 'Price', 'Day', 'Month', 'Year',
       'Arrival_hour', 'Arrival_minute'],
      dtype='object')

In [34]:
df['Dept_hour']= df['Dep_Time'].str.split(':').str[0]
df['Dept_minute']= df['Dep_Time'].str.split(':').str[1]

In [35]:
df.columns

Index(['Airline', 'Source', 'Destination', 'Route', 'Dep_Time', 'Duration',
       'Total_Stops', 'Additional_Info', 'Price', 'Day', 'Month', 'Year',
       'Arrival_hour', 'Arrival_minute', 'Dept_hour', 'Dept_minute'],
      dtype='object')

In [36]:
df['Dept_hour']=df['Dept_hour'].astype(int)
df['Dept_minute']=df['Dept_minute'].astype(int)

In [37]:
df.drop('Dep_Time',axis = 1 , inplace = True)

In [38]:
df.columns

Index(['Airline', 'Source', 'Destination', 'Route', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price', 'Day', 'Month', 'Year', 'Arrival_hour',
       'Arrival_minute', 'Dept_hour', 'Dept_minute'],
      dtype='object')

In [39]:
df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', '4 stops'],
      dtype=object)

In [40]:
df['Total_Stops'] = df['Total_Stops'].map({'non-stop':0,'1 stop':1,'2 stops':2,'3 stops':3,'4 stops':4})

In [41]:
df['Total_Stops']

0        0
1        2
2        2
3        1
4        1
        ..
10678    0
10679    0
10680    0
10681    0
10682    2
Name: Total_Stops, Length: 10682, dtype: int64

In [42]:
#Rout can be used in two ways 
#To know souce and destination >> already available
#To know the number of stops >> already available 
#So it is of no use.

In [43]:
df.drop('Route' , axis = 1 , inplace = True)

In [44]:
df.columns

Index(['Airline', 'Source', 'Destination', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price', 'Day', 'Month', 'Year', 'Arrival_hour',
       'Arrival_minute', 'Dept_hour', 'Dept_minute'],
      dtype='object')

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Duration         10682 non-null  object
 4   Total_Stops      10682 non-null  int64
 5   Additional_Info  10682 non-null  object
 6   Price            10682 non-null  int64
 7   Day              10682 non-null  int32
 8   Month            10682 non-null  int32
 9   Year             10682 non-null  int32
 10  Arrival_hour     10682 non-null  int32
 11  Arrival_minute   10682 non-null  int32
 12  Dept_hour        10682 non-null  int32
 13  Dept_minute      10682 non-null  int32
dtypes: int32(7), int64(2), object(5)
memory usage: 1.2+ MB

In [47]:
df['Duration']

0        2h 50m
1        7h 25m
2           19h
3        5h 25m
4        4h 45m
          ...
10678    2h 30m
10679    2h 35m
10680        3h
10681    2h 40m
10682    8h 20m
Name: Duration, Length: 10682, dtype: object

In [50]:
df['Duration_hour'] = df.Duration.str.split(' ').str[0].str.split('h').str[0]

In [52]:
df['Duration_minute'] = df.Duration.str.split(' ').str[1].str.split('m').str[0]

In [53]:
df.dtypes

Airline            object
Source             object
Destination        object
Duration           object
Total_Stops         int64
Additional_Info    object
Price               int64
Day                 int32
Month               int32
Year                int32
Arrival_hour        int32
Arrival_minute      int32
Dept_hour           int32
Dept_minute         int32
Duration_hour      object
Duration_minute    object
dtype: object

In [55]:
df['Duration_hour'].unique()

array(['2', '7', '19', '5', '4', '15', '21', '25', '13', '12', '26', '22',
       '23', '20', '10', '6', '11', '8', '16', '3', '27', '1', '14', '9',
       '18', '17', '24', '30', '28', '29', '37', '34', '38', '35', '36',
       '47', '33', '32', '31', '42', '39', '5m', '41', '40'], dtype=object)

In [57]:
df['Additional_Info']

0        No info
1        No info
2        No info
3        No info
4        No info
          ...
10678    No info
10679    No info
10680    No info
10681    No info
10682    No info
Name: Additional_Info, Length: 10682, dtype: object

In [58]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()

In [59]:
encoder

OneHotEncoder()

In [64]:
en_data = encoder.fit_transform(df[['Airline' , 'Source','Destination','Additional_Info']]).toarray()

In [65]:
col = encoder.get_feature_names_out()

In [68]:
ed = pd.DataFrame(en_data , columns = col)

In [70]:
df.drop(['Airline','Source','Destination','Additional_Info'],axis = 1 , inplace = True)

In [71]:
ed

,Airline_Air Asia,Airline_Air India,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,Airline_Jet Airways Business,Airline_Multiple carriers,Airline_Multiple carriers Premium economy,Airline_SpiceJet,Airline_Trujet,...,Additional_Info_1 Long layover,Additional_Info_1 Short layover,Additional_Info_2 Long layover,Additional_Info_Business class,Additional_Info_Change airports,Additional_Info_In-flight meal not included,Additional_Info_No Info,Additional_Info_No check-in baggage included,Additional_Info_No info,Additional_Info_Red-eye flight
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10677,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10678,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10679,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10680,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10681,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [73]:
final_df = pd.concat([df , ed] , axis = 1)

In [74]:
final_df.dtypes

Duration                                         object
Total_Stops                                     float64
Price                                           float64
Day                                             float64
Month                                           float64
Year                                            float64
Arrival_hour                                    float64
Arrival_minute                                  float64
Dept_hour                                       float64
Dept_minute                                     float64
Duration_hour                                    object
Duration_minute                                  object
Airline_Air Asia                                float64
Airline_Air India                               float64
Airline_GoAir                                   float64
Airline_IndiGo                                  float64
Airline_Jet Airways                             float64
Airline_Jet Airways Business                    float64
Airline_Multiple carriers                       float64
Airline_Multiple carriers Premium economy       float64
Airline_SpiceJet                                float64
Airline_Trujet                                  float64
Airline_Vistara                                 float64
Airline_Vistara Premium economy                 float64
Source_Banglore                                 float64
Source_Chennai                                  float64
Source_Delhi                                    float64
Source_Kolkata                                  float64
Source_Mumbai                                   float64
Destination_Banglore                            float64
Destination_Cochin                              float64
Destination_Delhi                               float64
Destination_Hyderabad                           float64
Destination_Kolkata                             float64
Destination_New Delhi                           float64
Additional_Info_1 Long layover                  float64
Additional_Info_1 Short layover                 float64
Additional_Info_2 Long layover                  float64
Additional_Info_Business class                  float64
Additional_Info_Change airports                 float64
Additional_Info_In-flight meal not included     float64
Additional_Info_No Info                         float64
Additional_Info_No check-in baggage included    float64
Additional_Info_No info                         float64
Additional_Info_Red-eye flight                  float64
dtype: object